const data =[
    {
        type:'Fire',
        name:'Ponyta',
        sprite:'https://www.pokepedia.fr/images/thumb/8/8f/Ponyta-RFVF.png/250px-Ponyta-RFVF.png',
        match:[1,2]
    },
    {
        type:'Water',
        name:'Squirtle',
        sprite:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRFUm-yBI1IpYJXHQJFfmlhH_F-x8FPjupWgQ&usqp=CAU',
        match:[2,3]
    },
    {
        type:'Grass',
        name:'Bulbasaur',
        sprite:'https://pm1.narvii.com/6778/329fd36057877fc1f90d1840c52baeea14e620b8v2_hq.jpg',
        match:[3,5]
    },
    {
        type:'Dragon',
        name:'Dratini',
        sprite:'https://img.favpng.com/4/15/5/dratini-pok-mon-yellow-dragonite-dragonair-pikachu-png-favpng-6BUf0dSVpj9B0rxd02nD1TGKs.jpg',
        match:[4]
    },
    {
        type:'Electric',
        name:'Joltik',
        sprite:'https://img.favpng.com/13/24/20/joltik-galvantula-bulbapedia-electric-image-png-favpng-ySfTsbuA5iMGQ3dPvdDSPeWja.jpg',
        match:[5]
    },
    {
        type:'Bug',
        name:'Weedle',
        sprite:'https://thumbnail.imgbin.com/25/2/12/imgbin-weedle-pokemon-black-white-pok-mon-go-kakuna-others-bPRg4g3mhuLDfPwMeVAYP1ipd_t.jpg',
        match:[6,4]
    },{
        type:'Rock',
        name:'Sudowoodo',
        sprite:'https://www.vhv.rs/dpng/d/555-5553537_sudowoodo-hd-png-download.png',
        match:[7,4]
    },{
        type:'Poison',
        name:'Nidoran',
        sprite:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHP7fGJUQDZtLlAZ3GqnG23v9yZgmxZP9oHw&usqp=CAU',
        match:[8]
    },{
        type:'Ground',
        name:'Phanpy',
        sprite:'https://www.pngitem.com/pimgs/m/514-5149535_image-freeuse-stock-ground-drawing-digital-painting-cutest.png',
        match:[9]

    },{
        type:'Flying',
        name:'Emolga',
        sprite:'https://listimg.pinclipart.com/picdir/s/220-2203049_pokemon-png-flying-clipart-butterfree-caterpie-video-pokemon.png',
        match:[10]
    },{
        type:'Normal',
        name:'Sentret',
        sprite:'https://pokemon3d.net/wiki/images/5/5c/Sentret.png',
        match:[11]
    },{
        type:'Ice',
        name:'Glaceon',
        sprite:'https://www.kindpng.com/picc/m/147-1478996_god-of-ice-type-pokemon-hd-png-download.png',
        match:[12]
    },{
        type:'Fighting',
        name:'Scrafty',
        sprite:'https://www.vhv.rs/dpng/d/49-494735_fighting-pokemon-hd-png-download.png',
        match:[13]
    },{
        type:'Psychic',
        name:'Jirachi',
        sprite:'https://www.ssbwiki.com/images/thumb/c/c3/Jirachi-Origin.png/1200px-Jirachi-Origin.png',
        match:[14]
    },{
        type:'Ghost',
        name:'Misdreavus',
        sprite:'https://www.pngitem.com/pimgs/m/397-3979198_misdreavus-pokemon-png-transparent-png.png',
        match:[15]
    },{
        type:'dark',
        name:'Umbreon',
        sprite:'https://archive-media-1.nyafuu.org/vp/image/1423/57/1423579071296.png',
        match:[16]
    },{
        type:'Steel',
        name:'Klink',
        sprite:'https://cdn.bulbagarden.net/upload/thumb/e/ea/599Klink.png/1200px-599Klink.png',
        match:[17]
    },{
        type:'Fairy',
        name:'Marill',
        sprite:'https://www.clipartkey.com/mpngs/m/25-259777_pokemon-clipart-translucent-pokemon-marill.png',
        match:[18]
    }

];
export default data;